name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test

          # Need to find a more reliable way to test as this fails to load often
          #    - name: Instrumented Test
          #      uses: reactivecircus/android-emulator-runner@v2
          #      with:
          #        profile: Galaxy Nexus
        #        api-level: 29
        #  script: ./gradlew connectedCheck
      - name: Build with Gradle
        run: ./gradlew build
